# Generated by Django 5.0.6 on 2024-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_todays_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='todays_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
