# Generated by Django 5.0.6 on 2024-06-10 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todays_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todays_view',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='todays_view',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='views',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='views',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
